In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("https://www.dropbox.com/s/09syh5fwp3ggp11/cleaned_airbnb.csv?dl=1")

In [5]:
df.head()

,Unnamed: 0,index,name,host_id,neighbourhood,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,days_since_last_review
0,0,0,"Lovely large room, Bethnal Green",264345,Tower Hamlets,Private room,55,3,65,0.47,1,74,0,2335.0
1,1,1,Holiday London DB Room Let-on going,54730,Islington,Private room,50,1,30,0.20,2,343,9,109.0
2,2,2,COSY STUDIO-FLAT WITH A GREAT VIEW,1481412,Tower Hamlets,Entire home/apt,90,5,42,0.34,1,222,1,301.0
3,3,3,A Luxury Studio Suite in Clerkenwell,259088,Islington,Private room,180,4,493,3.59,5,236,20,60.0
4,4,4,Notting Hill church stay in Heaven!,1481851,Kensington and Chelsea,Entire home/apt,297,14,6,0.05,1,180,2,120.0

In [3]:
df.columns

Index(['Unnamed: 0', 'index', 'name', 'host_id', 'neighbourhood', 'room_type',
       'price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365',
       'number_of_reviews_ltm', 'days_since_last_review'],
      dtype='object')

In [4]:
X_cat = ['neighbourhood', 'room_type']

In [5]:
for i in X_cat:
  one_hot = pd.get_dummies(df[i], drop_first = True).rename(columns=lambda x: i + '_' + str(x))
  df = pd.concat([df, one_hot], axis=1)
  df.drop([i], inplace=True, axis=1)

In [11]:
df.columns

Index(['Unnamed: 0', 'index', 'name', 'host_id', 'price', 'minimum_nights',
       'number_of_reviews', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365',
       'number_of_reviews_ltm', 'days_since_last_review',
       'neighbourhood_Barnet', 'neighbourhood_Bexley', 'neighbourhood_Brent',
       'neighbourhood_Bromley', 'neighbourhood_Camden',
       'neighbourhood_City of London', 'neighbourhood_Croydon',
       'neighbourhood_Ealing', 'neighbourhood_Enfield',
       'neighbourhood_Greenwich', 'neighbourhood_Hackney',
       'neighbourhood_Hammersmith and Fulham', 'neighbourhood_Haringey',
       'neighbourhood_Harrow', 'neighbourhood_Havering',
       'neighbourhood_Hillingdon', 'neighbourhood_Hounslow',
       'neighbourhood_Islington', 'neighbourhood_Kensington and Chelsea',
       'neighbourhood_Kingston upon Thames', 'neighbourhood_Lambeth',
       'neighbourhood_Lewisham', 'neighbourhood_Merton',
       'neighbourhood_Newham', 'neighbourhood_Redbridge',
       'neighbourhood_Richmond upon Thames', 'neighbourhood_Southwark',
       'neighbourhood_Sutton', 'neighbourhood_Tower Hamlets',
       'neighbourhood_Waltham Forest', 'neighbourhood_Wandsworth',
       'neighbourhood_Westminster', 'room_type_Hotel room',
       'room_type_Private room', 'room_type_Shared room'],
      dtype='object')

In [6]:
y = df['price']
X = df[['minimum_nights', 'number_of_reviews', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365',
       'number_of_reviews_ltm', 'days_since_last_review',
       'neighbourhood_Barnet', 'neighbourhood_Bexley', 'neighbourhood_Brent',
       'neighbourhood_Bromley', 'neighbourhood_Camden',
       'neighbourhood_City of London', 'neighbourhood_Croydon',
       'neighbourhood_Ealing', 'neighbourhood_Enfield',
       'neighbourhood_Greenwich', 'neighbourhood_Hackney',
       'neighbourhood_Hammersmith and Fulham', 'neighbourhood_Haringey',
       'neighbourhood_Harrow', 'neighbourhood_Havering',
       'neighbourhood_Hillingdon', 'neighbourhood_Hounslow',
       'neighbourhood_Islington', 'neighbourhood_Kensington and Chelsea',
       'neighbourhood_Kingston upon Thames', 'neighbourhood_Lambeth',
       'neighbourhood_Lewisham', 'neighbourhood_Merton',
       'neighbourhood_Newham', 'neighbourhood_Redbridge',
       'neighbourhood_Richmond upon Thames', 'neighbourhood_Southwark',
       'neighbourhood_Sutton', 'neighbourhood_Tower Hamlets',
       'neighbourhood_Waltham Forest', 'neighbourhood_Wandsworth',
       'neighbourhood_Westminster', 'room_type_Hotel room',
       'room_type_Private room', 'room_type_Shared room']]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
lr = LinearRegression().fit(X_train, y_train)

In [11]:
lr.score(X_train,y_train), lr.score(X_test, y_test)

(0.31293292244658855, 0.3112969091468595)

In [13]:
import statsmodels.api as sm

In [14]:
lr2 = sm.OLS(y_train, sm.add_constant(X_train))

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

In [15]:
result = lr2.fit()
print(result.summary2())

                             Results: Ordinary least squares
==========================================================================================
Model:                      OLS                     Adj. R-squared:            0.312
Dependent Variable:         price                   AIC:                       557045.9715
Date:                       2022-11-28 04:54        BIC:                       557420.9629
No. Observations:           45285                   Log-Likelihood:            -2.7848e+05
Df Model:                   42                      F-statistic:               490.9
Df Residuals:               45242                   Prob (F-statistic):        0.00
R-squared:                  0.313                   Scale:                     12862.
------------------------------------------------------------------------------------------
                                       Coef.   Std.Err.    t     P>|t|    [0.025   0.975]
------------------------------------------------------------------------------------------
const                                 122.5128   6.9566  17.6110 0.0000  108.8777 136.1478
minimum_nights                         -0.0852   0.0215  -3.9655 0.0001   -0.1274  -0.0431
number_of_reviews                      -0.1685   0.0171  -9.8762 0.0000   -0.2020  -0.1351
reviews_per_month                      -1.8343   0.6660  -2.7541 0.0059   -3.1396  -0.5289
calculated_host_listings_count          0.4211   0.0184  22.8727 0.0000    0.3850   0.4572
availability_365                        0.1979   0.0044  44.4953 0.0000    0.1892   0.2066
number_of_reviews_ltm                  -0.1198   0.0674  -1.7778 0.0754   -0.2520   0.0123
days_since_last_review                 -0.0191   0.0010 -19.3864 0.0000   -0.0211  -0.0172
neighbourhood_Barnet                   21.1008   7.6839   2.7461 0.0060    6.0402  36.1613
neighbourhood_Bexley                   -7.6828   9.6379  -0.7971 0.4254  -26.5732  11.2076
neighbourhood_Brent                    24.6113   7.5282   3.2692 0.0011    9.8558  39.3668
neighbourhood_Bromley                  11.8627   8.8376   1.3423 0.1795   -5.4592  29.1845
neighbourhood_Camden                   59.0533   7.1472   8.2624 0.0000   45.0446  73.0620
neighbourhood_City of London          104.7962   9.4966  11.0351 0.0000   86.1827 123.4098
neighbourhood_Croydon                  -4.1729   8.1256  -0.5136 0.6076  -20.0991  11.7533
neighbourhood_Ealing                   25.7887   7.7102   3.3448 0.0008   10.6767  40.9008
neighbourhood_Enfield                   2.4674   8.8807   0.2778 0.7811  -14.9389  19.8737
neighbourhood_Greenwich                16.3984   7.7447   2.1174 0.0342    1.2186  31.5782
neighbourhood_Hackney                  33.6696   7.1313   4.7214 0.0000   19.6922  47.6470
neighbourhood_Hammersmith and Fulham   55.9321   7.3191   7.6420 0.0000   41.5866  70.2776
neighbourhood_Haringey                 18.9950   7.5806   2.5057 0.0122    4.1369  33.8531
neighbourhood_Harrow                    1.0250   9.5231   0.1076 0.9143  -17.6405  19.6905
neighbourhood_Havering                 -4.2040  10.3263  -0.4071 0.6839  -24.4437  16.0356
neighbourhood_Hillingdon                0.5260   8.5578   0.0615 0.9510  -16.2474  17.2993
neighbourhood_Hounslow                 17.6501   8.0903   2.1816 0.0291    1.7929  33.5073
neighbourhood_Islington                41.1997   7.2307   5.6979 0.0000   27.0274  55.3721
neighbourhood_Kensington and Chelsea  109.2661   7.1706  15.2381 0.0000   95.2116 123.3205
neighbourhood_Kingston upon Thames     20.3568   8.9688   2.2697 0.0232    2.7778  37.9358
neighbourhood_Lambeth                  36.9260   7.2204   5.1141 0.0000   22.7738  51.0782
neighbourhood_Lewisham                  6.5669   7.5319   0.8719 0.3833   -8.1958  21.3297
neighbourhood_Merton                   41.9072   8.0107   5.2314 0.0000   26.2061  57.6083
neighbourhood_Newham                   47.7108   7.6511   6.2358 0.0000   32.7145  62.7071
neighbourhood_Redbridge                21.6200   8.7697   2.4653 0.0137    4.4313  38.8087
neighbourhood_Richmond upon Thames     42.0062   8.0345   5.2282 0.0000   26.2584  57.7540
neighbourhood_Southwark                40.8887   7.2237   5.6604 0.0000   26.7301  55.0472
neighbourhood_Sutton                   -0.7393  11.0477  -0.0669 0.9466  -22.3929  20.9143
neighbourhood_Tower Hamlets            38.6159   7.1048   5.4352 0.0000   24.6904  52.5413
neighbourhood_Waltham Forest            7.5331   7.8391   0.9610 0.3366   -7.8316  22.8978
neighbourhood_Wandsworth               50.1086   7.2452   6.9161 0.0000   35.9079  64.3093
neighbourhood_Westminster             116.9950   7.0452  16.6063 0.0000  103.1862 130.8037
room_type_Hotel room                   -2.4305   9.0531  -0.2685 0.7883  -20.1747  15.3136
room_type_Private room                -94.3174   1.1433 -82.4970 0.0000  -96.5583 -92.0765
room_type_Shared room                -107.9639   7.3540 -14.6810 0.0000 -122.3778 -93.5500
------------------------------------------------------------------------------------------
Omnibus:                    30577.723             Durbin-Watson:                2.020
Prob(Omnibus):              0.000                 Jarque-Bera (JB):             490419.276
Skew:                       3.081                 Prob(JB):                     0.000
Kurtosis:                   17.898                Condition No.:                67575
==========================================================================================
* The condition number is large (7e+04). This might indicate             strong
multicollinearity or other numerical problems.

In [28]:
X[['minimum_nights', 'number_of_reviews', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365',
       'number_of_reviews_ltm', 'days_since_last_review']].corr()

,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,days_since_last_review
minimum_nights,1.000000,-0.024963,-0.039257,0.023106,0.050937,-0.047574,0.019204
number_of_reviews,-0.024963,1.000000,0.431228,-0.035407,0.057590,0.618309,-0.188018
reviews_per_month,-0.039257,0.431228,1.000000,-0.012500,0.209418,0.661251,-0.419079
calculated_host_listings_count,0.023106,-0.035407,-0.012500,1.000000,0.080548,-0.016089,-0.073522
availability_365,0.050937,0.057590,0.209418,0.080548,1.000000,0.165702,-0.397058
number_of_reviews_ltm,-0.047574,0.618309,0.661251,-0.016089,0.165702,1.000000,-0.339005
days_since_last_review,0.019204,-0.188018,-0.419079,-0.073522,-0.397058,-0.339005,1.000000

In [16]:
# random forest regressor 
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(max_depth=2, random_state=0)
rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=2, random_state=0)

In [17]:
rf.score(X_train, y_train), rf.score(X_test, y_test)

(0.24561924997824025, 0.24550251835769654)

In [ ]:

###feature selection